### ISSUE TITLE
Add calendar picker option to textfields

### ISSUE THREAD

**Issue by bartreardon** [swiftDialog/swiftDialog#224]
Title 👆

**Comment by BigMacAdmin** [comment]
Being able to set a "no later than this" date would be great, but added complexity would be "Deadline" (hard and fast date) vs. "Future" (no more than 7 days out).

**Comment by kspitzer14** [comment]
7 days for "No Later Than" is good, but my users can be a bit... persnickety. 14 might be better.

**Comment by bartreardon** [comment]
the macOS implementation of the date picker in SwiftUI is notoriously fickle. I'm not setting my sights any higher than "allow the user to pick a date" but we'll see how we go.

**Comment by bartreardon** [comment]
initial implementation.

no validation or any other fancyness like date range - just takes the date value and puts it as text into the textfield.

<img width="727" alt="image" src="https://github.com/swiftDialog/swiftDialog/assets/3598965/72708271-d1e8-4cbf-b255-d8ba10659fa0">

**Comment by BigMacAdmin** [comment]
Date stuff is notoriously difficult based on region, timezone, etc.

Your screenshot shows this, since you're using Au formatting your January 2 shows as 2/1 while mine would show 1/2.

My 2 cents: This will be infinitely easier to program around if the return is a unix epoch time stamp. Wondering if you can also get the clock on their for a specific time selection. Giving back unix epoch time would make handling everything else programmatically a lot easier.

![image](https://github.com/swiftDialog/swiftDialog/assets/106293503/f7745e32-f4fb-424e-b5fe-fb3f1b19460e)

**Comment by bartreardon** [comment]
As mentioned in slack, unix epoch is where I'll be ultimately going with this. Just wanted to get the UX behaviour sorted first to make sure it's going to work before making too many under the hood changes to support it. 

The idea is when using a date, what gets displayed is a localised representation. What gets stored is the full date as a unix timestamp and that's what will get sent to output for processing. The data to do that is already stored, there's jsut no logic to expose that in the results yet 🙂

**Comment by bartreardon** [comment]
I'm closing this as done. Any future enhancements or changes can be handled in a specific issue.
