### ISSUE TITLE
Enter key can not be used to submit a text field

### ISSUE THREAD

**Issue by dnikles** [swiftDialog/swiftDialog#227]
When entering data in a text field, pressing the return key (above the right shift key) will submit, but pressing the enter key (far right on full sized keyboard in number pad area) will not.  If there isn't a text field, the enter key will submit.

`dialog "hello"` allows the enter key to dismiss the dialog window

`dialog --textfield "number"` does not allow the enter key to dismiss the dialog window

**Comment by bartreardon** [comment]
This is because textfields can have multiple lines of text.

with a regular `--textfield` this is limited to one line but if you initiate with an editor style `dialog --textfield "number",editor` The enter key will insert a new line.

There's potentially a case to be made that this behaviour should be reversed. and `return` should insert a new line and `enter` activate the default button, however this is the behaviour defined by the `KeyboardShortcut.defaultAction` which developer documentation defines as:

 > The standard keyboard shortcut for the default button, consisting of the Return (↩) key and no modifiers.

**Comment by dnikles** [comment]
> with a regular `--textfield` this is limited to one line but if you initiate with an editor style `dialog --textfield "number",editor` The enter key will insert a new line.

So does the return key. They behave the same when in editor style, but differently when not in editor style.

**Comment by bartreardon** [comment]
closing this as wontfix

**Comment by dnikles** [comment]
Why different behavior between editor style and not editor style?

**Comment by bartreardon** [comment]
With no input fields the default responder on the dialog is button1 and both `enter` and `return` will activate the button as it's the only interactive element on the window.

`return` always activates the default responder unless an editor field has focus. `enter` only activates on the focused element (which is why it works to close the dialog on windows with no input elements) 

in a single line text field, `return` has no action for adding a newline and so the default action takes over and closes the dialog (activates the default responder) `enter` has no effect since there's only one line so no newlines are entered and it has no control over the default responder action, which is allocated to the `return` key

in a multi line text field (i.e. editor), `return` _can_ enter in a newline and this action takes precedence over whatever default assignment it has (i.e. actioning button1 to close the window). `return` acts as it should and inserts a new line.

**Comment by bartreardon** [comment]
I might add that to the wiki actually

**Comment by bartreardon** [comment]
https://github.com/swiftDialog/swiftDialog/wiki/Buttons-and-button-behaviour#behaviour-of-return-and-enter-keys

**Comment by dnikles** [comment]
Lots of programs use the number pad for data entry. That's not possible for
anything using swiftdialog. This design decision detracts from the
usefulness of swiftdialog. I'd like you to reconsider, but understand this
is your project.
