### ISSUE TITLE
Image as part of message

### ISSUE THREAD

**Issue by starlord1980** [swiftDialog/swiftDialog#343]
I need a larger image than the icon as I'm trying to convey instructions to staff members that they must complete. Preferably an image in the body of the message would be better, is this possible to do?

This is as far as I've got at the moment but the icon size is too small:
`dialog --icon "https://i.stack.imgur.com/hi3IJ.png" --iconsize=1000 -s --title "Company Message PLEASE READ"  --message "Software has been updated. Please go to System Settings > Privacy & Security and click \'Allow\'. You may be prompted to reboot your computer." --checkbox "I Will Follow These Instructions",enableButton1 --button1disabled`

**Comment by mm2270** [comment]
You can add an image into a dialog instead of trying to use an icon.

```
dialog --image https://i.stack.imgur.com/hi3IJ.png --title "Company Message PLEASE READ"  --message "Software has been updated. Please go to System Settings > Privacy & Security and click \'Allow\'. You may be prompted to reboot your computer." --checkbox "I Will Follow These Instructions",enableButton1 --button1disabled --icon none --height 700
```
<img width="932" alt="Screen Shot 2024-02-07 at 12 40 25 PM" src="https://github.com/swiftDialog/swiftDialog/assets/3653600/4a5d01f8-3cb9-444d-9423-dea2eefff7dc">

Note that to get this to work I added `--icon none` and `--height 700`. If you leave the dialog at the default height, the image still shows up kind of small to fit the height of the dialog.

**Comment by starlord1980** [comment]
Ahh, perfection. I didnt see that option.
Thanks!
