### ISSUE TITLE
Allow checkboxes to scroll

### ISSUE THREAD

**Issue by wakco** [swiftDialog/swiftDialog#464]
I'm trying to setup a dialog to allow uninstallation of installed Adobe apps, however the best option currently available to list the installed apps and provide a means of selecting one or several of the apps to "uninstall", is checkboxes, however with more than 20 possible Adobe apps that could be installed with the possibility of much more when someone leaves older versions installed where the year is attached to the name of the app, the window ends up quite large, and the checkbox section doesn't currently allow scrolling, which would help with managing the window size.

I will log a seperate version of this request to allow list items to be selectable as a better variation of this idea.

**Comment by bartreardon** [comment]
this is what `--checkboxstyle switch` is for. 

Following apple guidelines, checkboxes remain fixed to the window surface whereas switches can be contained in a scrollable area.

**Comment by wakco** [comment]
I figured, but I'm not getting a scroll bar with the switch option. (The listitems version of this is issue #465.)

**Comment by bartreardon** [comment]
it scrolls for me 

```
dialog --checkbox 1 --checkbox 2 --checkbox 3 --checkbox 4 --checkbox 4 --checkbox 5 --checkbox 6 --checkbox 7 --checkbox 8 --checkbox 9 --checkbox 10 --checkbox 11 --checkbox 12 --checkbox 13 --checkboxstyle switch
```

<img width="932" alt="image" src="https://github.com/user-attachments/assets/b05f39c6-33c2-4ee1-b17f-31f55c4bd9e4">

can you provide an example where it's not working?

Internally it determines that if the content of the switch view is going to be more than the available window space it will place them in a scrollview, otherwise it doesn't - e.g. 2 or 3 switches probably won'y scroll but more will. If you add a bunch of switches and include the `--resizable` flag you can see this in action as you change the height of the window.

**Comment by wakco** [comment]
**grumble** now it's working and I can't replicate when it wasn't working. Thanks, closed.

**Comment by bartreardon** [comment]
gotta love those ones 😛
