### ISSUE TITLE
Empty strings configured to match regex patterns do not block pane closure

### ISSUE THREAD

**Issue by FranckSartori** [swiftDialog/swiftDialog#482]
Hi.

Currently, swiftDialog 2.5.5 is being used.

Based on the following example :

`/usr/local/bin/dialog --width 700 --height 476 --moveable --ontop --titlefont size=20 --messagefont size=14 --title 'A' --message 'B' --jsonstring '{"textfield" : [{"title" : "C", "regex" : "^\\d{6}$", "regexerror" : "Asset Tag must be a six-digit number.", "value" : ""}]}' --button1text OK --json`

The validation works when the fields are filled in, but it is still possible to close the pane without entering any values in the fields.

The documentation says :
NOTE: Unless the regex allows it, using regex implies that the field cannot be empty, and the error prompt will be displayed if no entry is made.

My expectation is that it should not be possible to close the pane without entering values in the fields, ensuring that a REGEX implies the field is required.

Regards.

Franck

**Comment by bartreardon** [comment]
I think the documentation is incorrect. The behaviour for regex is it will match either the pattern or an empty value. If you don't want an empty value then acc a `required` condition on the textfield.

This has been the intended behaviour since regex was added, save for a very early iteration which is likely when the documentation was written.

**Comment by FranckSartori** [comment]
Hi. Perfect! I’ve updated my code to handle regex and required fields independently, so everything works as intended now. I just wanted to confirm before making changes, and it’s great to have that level of granularity. Regards. Franck
